trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Library Common Vars'

steps:
  - task: PowerShell@2
    displayName: 'Publish to Nuget'
    inputs:
      filePath: 'build.ps1'
      arguments: '-Target PushToNuget'
      pwsh: true
